name: Build and test Pipeline

on:
  pull_request:
    branches: 
      - master

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
  
      - name: Install dependencies 
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release --no-restore
  
  test:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: dotnet test --configuration Release
