name: Build and test Pipeline

on:
  pull_request:
    branches: 
      - master

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      build-path: ${{ steps.upload-artifact.outputs.artifact-path }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
  
      - name: Install dependencies 
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Upload build output
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: |
            **/bin/Release/
  
  test:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Download build output
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: ./build

      - name: Test
        run: dotnet test --configuration Release
